version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
        auth:
          username: cesarinag
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Creating snyk-to-html report
          command: |
            npm install snyk -g;
            npm install snyk-to-html -g;
            snyk auth $SNYK_TOKEN;
            snyk test --json | snyk-to-html -o results.html

      - store_artifacts:
          path: results.html
          destination: results.html