version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
        auth:
          username: cesarinag
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    working_directory: /tmp
    steps:
      - run:
          name: Creating snyk-to-html reports
          command: |
            npm install snyk -g;
            npm install snyk-to-html;
            snyk auth $SNYK_TOKEN;
            snyk code test --sarif > results_code.sarif || true;
            snyk-to-html -i results_code.sarif -o results_code.html || true;
            snyk iac test . --json | snyk-to-html -o results_iac.html || true;
            snyk container test cesarinag/juice-shop:7.17.22 --json | snyk-to-html -o results_container.html || true;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
