version: 2.1
orbs:
  artifacts: eddiewebb/artifacts@0.1.53
jobs:
  build:
    docker:
      - image: node:latest
        auth:
          username: cesarinag
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - run:
          name: Creating snyk-to-html reports
          command: |
            mkdir ~/artifacts;
            npm install snyk -g;
            npm install snyk-to-html -g;
            snyk auth $SNYK_TOKEN;
            snyk test --json | snyk-to-html -o results.html

      - store_artifacts:
          path: ~/artifact-1
          destination: results.html

      - store_artifacts:
          path: ~/artifacts