# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  runsnyk:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies, snyk cli, snyk-to-html and authenticate
          command: |
                    'npm install snyk -g'
                    'npm install snyk-to-html'
                    'snyk auth ${SNYK_TOKEN}'
                    'snyk code test --sarif  > results_code.sarif || true'
                    'snyk-to-html -i results_code.sarif -o results_code.html || true'
                    'snyk test monitor --all-projects --json | snyk-to-html -o results_sca.html || true'
                    'snyk iac test . --json | snyk-to-html -o results_iac.html || true'
                    'snyk container test cesarinag/juice-shop:7.17.22 --json | snyk-to-html -o results_container.html || true'
      - snyk/scan:
          fail-on-issues: false              
workflows:
  test:
    jobs:
      - runsnyk